export {default as AddTask} from './Add-Task';
export {default as Auth} from './Auth';
export {default as Error} from './Error';
export {default as Home} from './Home';
export {default as HomeLayout} from './HomeLayout';
export {default as Landing} from './Landing';
export {default as Profile} from './Profile';
export {default as ProtectedRoute} from './ProtectedRoute';
export {default as Task} from './Task';